# 워크플로우 이름
name: Daily SSG Scraper

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # ##############################################################
          # ## 여기를 수정했습니다! (라이브러리 변경) ##
          # ##############################################################
          pip install pandas selenium supabase webdriver-manager
          # ##############################################################

      - name: Run Python Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python ssg-icn.py
