# 워크플로우 이름
name: Daily SSG Scraper

on:
  schedule:
    # cron 스케줄 문법: 매일 아침 10시(KST)는 UTC 기준 새벽 1시입니다.
    - cron: '0 1 * * *'
  # "Actions" 탭에서 수동으로 실행할 수도 있게 함
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ##############################################################
      # ## 여기를 수정했습니다! (파이썬 버전 변경) ##
      # ##############################################################
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 3.12에서 3.11로 버전을 변경합니다.
      # ##############################################################

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas undetected-chromedriver supabase

      - name: Run Python Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python ssg-icn.py
